// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ColorSelector: typeof import('./src/components/ColorSelector.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    CustomInfiniteLoading: typeof import('./src/components/CustomInfiniteLoading.vue')['default']
    CustomPagination: typeof import('./src/components/CustomPagination.vue')['default']
    DrawingPalette: typeof import('./src/components/DrawingPalette.vue')['default']
    GameActions: typeof import('./src/components/GameActions.vue')['default']
    GameCountdowns: typeof import('./src/components/GameCountdowns.vue')['default']
    GameNotification: typeof import('./src/components/GameNotification.vue')['default']
    GameOverModal: typeof import('./src/components/GameOverModal.vue')['default']
    InteractionInfo: typeof import('./src/components/InteractionInfo.vue')['default']
    LabelMintStatus: typeof import('./src/components/LabelMintStatus.vue')['default']
    ListStats: typeof import('./src/components/ListStats.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MintInformation: typeof import('./src/components/MintInformation.vue')['default']
    ModalClaimConfirmation: typeof import('./src/components/modals/ModalClaimConfirmation.vue')['default']
    ModalDialog: typeof import('./src/components/modals/ModalDialog.vue')['default']
    ModalExport: typeof import('./src/components/modals/ModalExport.vue')['default']
    ModalGameOver: typeof import('./src/components/modals/ModalGameOver.vue')['default']
    ModalMint: typeof import('./src/components/modals/ModalMint.vue')['default']
    ModalOpenEgg: typeof import('./src/components/ModalOpenEgg.vue')['default']
    ModalRedeemInfo: typeof import('./src/components/modals/ModalRedeemInfo.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NFTPreview: typeof import('./src/components/NFTPreview.vue')['default']
    PanelSlider: typeof import('./src/components/PanelSlider.vue')['default']
    PixelBoard: typeof import('./src/components/PixelBoard.vue')['default']
    PlayerGlobalData: typeof import('./src/components/PlayerGlobalData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    SubtabButton: typeof import('./src/components/SubtabButton.vue')['default']
    SvgImage: typeof import('./src/components/SvgImage.vue')['default']
    TabButton: typeof import('./src/components/TabButton.vue')['default']
    TimeLeft: typeof import('./src/components/TimeLeft.vue')['default']
    WitnetMarquee: typeof import('./src/components/WitnetMarquee.vue')['default']
    WitnetStrip: typeof import('./src/components/WitnetStrip.vue')['default']
    WittyCreature: typeof import('./src/components/WittyCreature.vue')['default']
    WittyPixelsLogo: typeof import('./src/components/WittyPixelsLogo.vue')['default']
  }
}

export {}
