name: staging

on:
  push:
    branches:
      - main

jobs:
  staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Deployment Files
        shell: bash
        env:
          LOKI: ${{ secrets.STAGING_LOKI_URL }}
          CADDY: ${{ secrets.STAGING_CADDY_FILE }}
          AINV: ${{ secrets.STAGING_ANSIBLE_INVENTORY }}
          APKEY: ${{ secrets.STAGING_ANSIBLE_PRIVATE_KEY }}
          ENVARS: ${{ secrets.STAGING_ENVIRONMENT_VARIABLES }}
        run: |
          echo "$ENVARS" > ./ansible/.env
          echo "$APKEY" > ./ansible/key.pem
          echo "$ENVARS" > ./packages/ui/.env
          echo "$CADDY" > ./ansible/Caddyfile
          echo "$ENVARS" > ./packages/api/.env
          echo "$AINV" > ./ansible/inventory.ini
          chmod 400 ./ansible/key.pem
          sed -i "s#LOKI-REPLACE-ME#$LOKI#g" ./ansible/docker-compose.yml

      - name: Build Containers
        run: |
          docker build -t witnet/witty-pixels-ethdenver-2023-ui:latest -f ./ansible/docker/ui.dockerfile ./packages/ui
          docker build -t witnet/witty-pixels-ethdenver-2023-api:latest -f ./ansible/docker/api.dockerfile ./packages/api

      - name: Publish Containers
        run: |
          docker push witnet/witty-pixels-ethdenver-2023-ui:latest
          docker push witnet/witty-pixels-ethdenver-2023-api:latest

      - name: Deploy with Ansible
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd ansible
          ansible-galaxy install -r requirements.yml
          export ANSIBLE_CONFIG=./ansible.cfg
          export ANSIBLE_FORCE_COLOR=True
          export ANSIBLE_STDOUT_CALLBACK=yaml
          export FORCE_COLOR=1
          export TERM=xterm-color
          ansible-playbook ./helper/docker-playbook.yml -vv
          ansible-playbook playbook.yml -vv